<?php
include("../../../myDatabase.php");
session_start();
$registrationNo = $_GET['registrationNo'];
$ro = new database();
$ro->getPatientProfile($registrationNo);
$ro->coconutDesign();
$ro->coconutHeading("User Verification","COCONUT/NURSING/initializeNursing.php");
unset($_SESSION['registrationNo']);
session_destroy();
echo "<Br>";
echo "<center>";
$ro->coconutImages("lock2.jpeg");
echo "&nbsp;<font size=2 color=red>Pls Login first to access the Profile of ".$ro->getPatientRecord_lastName().", ".$ro->getPatientRecord_firstName()." in ".$ro->getRegistrationDetails_room()." </font>";

echo "<br>";
$ro->coconutFormStart("post","verifyUser1.php");
$ro->coconutHidden("registrationNo",$registrationNo);
$ro->coconutBoxStart("500","150");
echo "<br><table border=0>";
echo "<tr>";
echo "<Td>".$ro->coconutText("Username")."</tD>";
echo "<td>";
$ro->coconutTextBox("username","");
echo "</td>";
echo "</tr>";
echo "<tr>";
echo "<td>".$ro->coconutText("Password")."</td>";
echo "<td>";
echo "<input type=password name='password' class='txtBox' value=''>";
echo "</td>";
echo "</tr>";
echo "<tr>";
echo "<td>".$ro->coconutText("Module")."</td>";
echo "<td>";
$ro->coconutComboBoxStart_long("module");
echo "<option value='NURSING'>Nursing Service</option>";
echo "<option value='REGISTRATION'>Registration</option>";
echo "<option value='BILLING'>Billing</option>";
echo "<option value='DOCTOR'>Doctor's Lounge</option>";
echo "<option value='LABORATORY'>Laboratory</option>";
echo "<option value='RADIOLOGY'>Radiology</option>";
echo "<option value='PHARMACY'>Pharmacy</option>";
echo "<option value='CSR'>CSR</option>";
echo "<option value='PATIENT'>Patient</option>";
echo "<option value='CASHIER'>Cashier</option>";
echo "<option value='MAINTENANCE'>Maintenance</option>";
echo "<option value='ADMIN'>Admin</option>";
$ro->coconutComboBoxStop();
echo "</td>";
echo "</tr>";
echo "</table>";
echo "<br>";
$ro->coconutButton("Proceed");
$ro->coconutBoxStop();
$ro->coconutFormStop();
?>
